apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
      - name: backend
        # Remplace par le nom exact de ton image locale (ex: todo-backend:latest)
        image: tasks-todo-backend:latest 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: "db-service" # Doit correspondre au nom du Service de la DB
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "todoapp"
        - name: DB_USER
          value: "todouser"
        - name: DB_PASSWORD
          value: "todopassword123"
        - name: BACKEND_PORT
          value: "5000"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: todo-backend
  # Fil backend-service.yaml beddel el type
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30005 # El API twalli f http://localhost:30005