apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_DB
          value: "todoapp"
        - name: POSTGRES_USER
          value: "todouser"
        - name: POSTGRES_PASSWORD
          value: "todopassword123"
        ports:
        - containerPort: 5432
        # --- ADD THIS PART ---
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data # Standard path for Postgres data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc # This MUST match the name in your db-storage.yaml